/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.toolkt

import kotlin.test.Test
import kotlin.test.assertTrue

class CoreTestsJs {
    @Test
    fun testGreetingJs() {
        val classUnderTest = Core()

        assertTrue(
            classUnderTest.greeting.endsWith("[JS]"),
        )
    }
}
