/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.toolkt

import kotlin.test.Test
import kotlin.test.assertTrue

class CoreTestsJvm {
    @Test
    fun testGreetingJvm() {
        val core = Core()

        assertTrue(
            core.greeting.endsWith("[JVM]"),
        )
    }
}
