/*
 * This source file was generated by the Gradle 'init' task
 */
package dev.toolkt

import kotlin.test.Test
import kotlin.test.assertTrue

class CoreTests {
    @Test
    fun testGreeting() {
        val core = Core()

        assertTrue(
            core.greeting.startsWith("Hello"),
        )
    }
}
