/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

class Core {
    val platform = Platform()

    val greeting: String
        get() {
            return "Hello World! [${platform.name}]"
        }
}

fun main() {
    println(Core().greeting)
}
